# Generated by Django 4.2.23 on 2025-06-10 23:57

from django.db import migrations

def populate_data(apps, schema_editor):
    Role = apps.get_model('members', 'Role')
    Member = apps.get_model('members', 'Member')
    Team = apps.get_model('teams', 'Team')

    Role.objects.create(name="Admin", description="Can delete members")
    Role.objects.create(name="Regular", description="Can't delete members")

    default_team = Team.objects.first()
    admin_role = Role.objects.get(name="Admin")
    Member.objects.create(name="Jane", lastname="Doe", email="jane.doe@email.com", phone="5620345677", team=default_team, role=admin_role)


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('teams', '0002_populate_initial_data')
    ]

    operations = [
        migrations.RunPython(populate_data),
    ]
