# Generated by Django 4.2.23 on 2025-06-13 22:35

from django.db import migrations, models

class Migration(migrations.Migration):
    """
    Before running this migration we must ensure no members
    wih duplicate emails exist. A manual clean up might be
    necessary.
    """

    dependencies = [
        ("members", "0002_populate_initial_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
