# Generated by Django 4.2.23 on 2025-06-10 23:54

from django.db import migrations

def populate_data(apps, schema_editor):
    Team = apps.get_model('teams', 'Team')
    Team.objects.create(name="The First")


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_data),
    ]
